# Numpy
Matrix manipulation

- Initializing matrix
- Random matrix
- Matrix Addition, Multiplication and Concatenation

Video: https://www.youtube.com/watch?v=kxQ-HOENUIQ

In [2]:
import numpy as np

A = np.ones((3,2))
print(A)

A = np.zeros((3,2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
A = np.eye(3)
print(A)

A = np.diag([3,2,5])
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3 0 0]
 [0 2 0]
 [0 0 5]]


In [4]:
B = np.random.random((3,2))
print(B)

print(B.T)

[[0.35838758 0.44428069]
 [0.68095958 0.94628009]
 [0.33360207 0.68993096]]
[[0.35838758 0.68095958 0.33360207]
 [0.44428069 0.94628009 0.68993096]]


In [5]:
print(B, '\n')

print(B[0, 0])
print(B[1,0])
print(B[-1, -1])
print(B[0,:])
print(B[:,1])


[[0.35838758 0.44428069]
 [0.68095958 0.94628009]
 [0.33360207 0.68993096]] 

0.3583875824570223
0.6809595828025373
0.6899309602429873
[0.35838758 0.44428069]
[0.44428069 0.94628009 0.68993096]


## Matrix Addition
$C = A^{\intercal} + 2B$

In [6]:
A = np.ones((2,3))
B = np.random.random((3,2))
C = A.T + 2*B
print(A)
print(B)
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.30162281 0.12657757]
 [0.58619487 0.15097219]
 [0.27951592 0.10816549]]
[[1.60324562 1.25315513]
 [2.17238974 1.30194439]
 [1.55903185 1.21633098]]


## Matrix Multiplication
$C = AB$

In [7]:
C = A.dot(B)   # Dot product 
print(C)

[[1.1673336  0.38571525]
 [1.1673336  0.38571525]]


In [8]:
C = A.T * B     # Element-wise product
print(C)

[[0.30162281 0.12657757]
 [0.58619487 0.15097219]
 [0.27951592 0.10816549]]


## Matrix Concatenation
$C = [A^{\intercal},  B]$

In [11]:
#print(A.T.shape, B.shape)
C = np.concatenate((A.T,B), axis=1)
D = np.concatenate((A.T,B), axis=0)
#print(C)
print(D)

[[1.         1.        ]
 [1.         1.        ]
 [1.         1.        ]
 [0.30162281 0.12657757]
 [0.58619487 0.15097219]
 [0.27951592 0.10816549]]


In [10]:
# Concatenating Vectors
a = np.ones(4)
b = np.array([2,3,4,5])
X = np.hstack([a,b])
Y = np.vstack([a,b])
print(X)
print(Y)

[1. 1. 1. 1. 2. 3. 4. 5.]
[[1. 1. 1. 1.]
 [2. 3. 4. 5.]]
